### ISSUE TITLE
Log XBE Region cause REGION ERROR

### ISSUE THREAD

**Issue by jarupxx** [Cxbx-Reloaded/Cxbx-Reloaded#776]
@ergo720 PR # 763 causes problems for XBE Region each XDK version 4831 or lower.
Unknown Region value written in HLECache.
I used the Nightcaster XDK 4039 PAL for the test case.
Region 4 is okay for PAL, but 40edba0.

PR #763 HLECache
```
[Certificate]
Name=Nightcaster
TitleID=4d530008
Region=40edba0
```
Previous commit 6a798ad55e38697e83d6625117c5c64a696f401f HLECache.
```
[Certificate]
Name=Nightcaster
TitleID=4d530008
Region=4
```
Ini file is not allowed attached, so they are zipped.
[9e11d219.ini-PR #763.zip](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1414054/9e11d219-PR.763.zip)
[KrnlDebug-PR #763.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1414059/KrnlDebug-PR.763.txt)
[9e11d219.ini-Previous commit.zip](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1414055/9e11d219-Previous.commit.zip)
[KrnlDebug-Previous commit.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1414060/KrnlDebug-Previous.commit.txt)
[Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1414088/Xbe.txt)

**Comment by jarupxx** [comment]
Yes, I’m sure fe7ef86561bbb1fa947d5b330d26c09d3a187958 in #763.

**Comment by ergo720** [comment]
In dead or alive 3 I'm able to reproduce the issue even in commit 6a798ad55e38697e83d6625117c5c64a696f401f (from Luke, jsrf patch) so I belive it's unrelated to my commit
[47cc79f4.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1414236/47cc79f4.txt)
[Dead or Alive 3-47cc79f4.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1414237/Dead.or.Alive.3-47cc79f4.txt)

**Comment by jarupxx** [comment]
Your commit is irrelevant. I'm also able to reproduce with commit 6a798ad which I grab from appveyor not my build.

**Comment by jarupxx** [comment]
Perhaps the issue occurs between commit ff52f93c81e020dbd17713d87924ab4b3026b939 and a4fa55519d700735021dc035765de12f3987941c. Previous commit 8b11cce5b6b0c5d59081cae66891068fbd2b6dea is still safe.

**Comment by PatrickvL** [comment]
Could https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/4b35db183c0a91f62165219dc610f83ba2785d2f be the cause, when @LukeUsher changed the Xbe.h header struct?

**Comment by RadWolfie** [comment]
The real question is... why is debug build working fine while release build is giving us wrong region? I had seen it happened in the past, I thought it was fixed awhile ago or was seeing things...

I had a look in g_pCertificate address where it got the first assignment, it was already wrong. Apparently, it's happening "before" `CxbxKrnlInit` was called.

I made a check right before `StoreXbeImageHeader` was called in `CxbxKrnlMain` function. Turns out the data is not alternated. Next thing I did is make a memory breakpoint for any editing to region AND game rating address location. (game rating had been alternated in release too.)

So now I found the source of the problem. It is inside `RestoreExeImageHeader` function with this code line.
`ExeOptionalHeader->DataDirectory[IMAGE_DIRECTORY_ENTRY_TLS] = NewOptionalHeader->DataDirectory[IMAGE_DIRECTORY_ENTRY_TLS];` To make it easy to locate it, [here's the link to source code](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/04e14338d0bcb2267258e9cc1f72b2eba483c71b/src/CxbxKrnl/CxbxKrnl.cpp#L235).
Here's the commit a3aad91231dd8fa59c6b12de23b3eac68b0a713a of cause the issue base on specific chunk of changes (from blame button). I'm not sure original CxbxKrnl.DLL indeed has `RestoreExeImageHeader` function?

That's what I have found so far for the day.

**Comment by PatrickvL** [comment]
Thank you very much! Good detective work. Alas, this function is required and cannot be removed, not even if we would be running using a loader. The values that are restored, keep Windows happy about our process, even though we've kicked out most of the windows executable image header, and replaced it with Xbox Xbe header data.
So, we'll have to find a way to do less damage, or to offer another source for these values, I'm afraid...

**Comment by RadWolfie** [comment]
I don't think this is about Windows. I had tried 2 of 5849 titles, both are showing correct region flag. Then tested 2 titles (4039 and 3937), both are showing region error. (Tested 5 times each title with no change.) @jarupxx's point is still valid. I believe @LukeUsher mentioned TLS method is still wrong?

**Comment by LukeUsher** [comment]
The certificate size/header sizes may change between XDK versions (they have at least once, to add new anti-piracy flags), that could explain why it only effects some XDK versions.

TLS is still wrong, but that has nothing to do with this issue, it is allocated in a region that won't conflict with any XBE data, but not in the location XAPI expects it to be.

**Comment by LukeUsher** [comment]
Note that even though the xbe certificate is being corrupted here, an unaltered copy is always accessible from the CxbxKrnl_Xbe->m_Certificate, so the HLE code could be updated to read from CxbxKrnl_Xbe->m_Certificate.dwGameRegion, rather than using the copy at the xbe base address.

**Comment by RadWolfie** [comment]
Okay, I'll fix this issue in a bit.

**Comment by RadWolfie** [comment]
Um... I have discover a new problem. `ApplyMediaPatches` function is using `g_pCertificate->dwGameRegion` where its editing right after TLS is set. I believe this is causing problem with TLS. Only workaround I can do is check the dwGameRegion value is still the same then call `MediaPatches`.

Strange thing is, it has no effect when `MediaPatches` is commented out.

**Comment by LukeUsher** [comment]
I think you're confusing the Windows EXE headers with Xbox TLS, they are different things and this is completely 100% unrelated to Xbox TLS emulation. ApplyMediaPatches is required to bypass anti-piracy checks at this moment in time, and does function acceptable: If it did not, many games would not boot at all!

Any writes to g_pCertificate->dwGameRegion, and any reads by Xbox code need to stay the same for now, but any reads for HLE purposes (hleintercept.cpp) or xbe dumps needs to read from CxbxKrnl_Xbe->m_Certificate.

Sorry for the confusion.

**Comment by RadWolfie** [comment]
This is the calling process
- CxbxKrnlMain
  - RestoreExeImageHeader (Edit g_pCertificate->dwGameRegion address to be TLS address)
  - CxbxKrnlInit
    - ApplyMediaPatches (Edit g_pCertificate->dwGameRegion address to allow all regions aka overwrite TLS address from `RestoreExeImageHeader` function)

Do you see the problem?

**Comment by RadWolfie** [comment]
Here's a proposal fix. https://github.com/RadWolfie/Cxbx-Reloaded/commit/ce06ab456a6b44ab94e2922cc5fbc409c139ae96 If acceptable, I'll create a pull request to fix this general issue.

**Comment by PatrickvL** [comment]
I see - the *Windows* TLS is restored, but for the titles, that address is used for the Xbe game region.
I'm in doubt about how to make this work at all times...
One solution could be to relocate the Xbe image NT header, much like how I did that with the running exe. But I'm not sure if all titles acknowledge relative addresses of Xbe image header fields - if not, Xbox accesses to the game region field will be done at this fixed address that contains the windows TLS pointer. Not good. If titles do acknowledge Xbe image header offsets, then we could move it aside such, that it will reside at a dedicated address without any overlapping usage

**Comment by PatrickvL** [comment]
dwCertificateAddr could be patched, when it turns out that the certificate contents would overlap with any of the three required exe fields.

**Comment by RadWolfie** [comment]
Hmm... I believe I do agree with you, since Certificate header is pretty much a read only structure. I'm trying it out now.

**Comment by RadWolfie** [comment]
No regression and it is indeed reading correctly. I'll make a commit in my other branch soon to be merge.

**Comment by PatrickvL** [comment]
Wow, nice work!

**Comment by PatrickvL** [comment]
Even though this is now solved, there's still the issue that this didn't happen in two 5849 titles which could indicate Luke's remark is spot-on : that the certificate size and/or location inside the Xbe header changed at some point.

In all cases in which there won't be a conflict between the three mandatory Windows exe fields and the Xbe certificate (and thus no corruption will happen) it's still safer not to reroute the certificate address.
Hence, the current fix should only be applied when required (only when overlap is going to happen).
Not an urgent matter, but we shouldn't leave it like this either
